#encoding: utf-8

HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'db_02'
USERNAME = 'root'
PASSWORD = '051545'
DB_URI = 'mysql+mysqlconnector://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)
SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = True